### ISSUE TITLE
Add contributions

### ISSUE THREAD

**Issue by dhrxvjhx** [dhrxvjhx/genesis1.0#2]

**Comment by dhrxvjhx** [comment]
@all-contributors please add @dhrxvjhx for code

**Comment by dhrxvjhx** [comment]
@all-contributors 
please add @JayabrataBasu for code, ideas.
please add @nikunjmathur08 for code, design, video.
please add @kushagrapokera for code.
please add @dhrxvjhx for doc, design.

**Comment by nikunjmathur08** [comment]
@all-contributors please add @kushagrapokera for code.

**Comment by nikunjmathur08** [comment]
@all-contributors please add @kushagrapokera for code.

**Comment by nikunjmathur08** [comment]
@all-contributors please add @endlaynavam15 for code.
